# Generated by Django 4.2.7 on 2023-12-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
