# Generated by Django 4.2.7 on 2023-12-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_viewerusers'),
        ('location_app', '0002_alter_locations_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
