# Generated by Django 4.2.7 on 2023-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerusers',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
