# Generated by Django 4.2.7 on 2023-12-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_alter_locations_userid'),
        ('users_app', '0004_alter_viewerusers_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewerUsers',
        ),
    ]
