version: '3.9'
services:
  web_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgresql_db:
          condition: service_started
    restart: always

  postgresql_db:
    image: postgres
    restart: always
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
