# Generated by Django 4.2.7 on 2023-12-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_viewerusers'),
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.viewerusers'),
        ),
    ]
