# Generated by Django 4.2.7 on 2024-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0005_alter_locations_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
