# Generated by Django 4.2.7 on 2024-01-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0006_alter_locations_latitude_alter_locations_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Latitude',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Longitude',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
